### ISSUE TITLE
Import of iqm with separated animations?

### ISSUE THREAD

**Issue by poVoq** [ccxvii/asstools#4]
iqm has the option of storing the animations for a rig in a seperate .iqm file (to use accross multiple meshes with the same rig), but importing these results in an error.

The best would be if one could import the main mesh & rig  (works now), and if you import further .iqm files containing only animations, then these are added to the action editor as separate animations.

**Comment by ccxvii** [comment]
IQM binary files containing only animations don't always have the skeleton definition, which means that the blender importer can't match up the bones. Once an armature has been created in blender, the original IQM bone numbering is not available anymore. The joints/bones are only referred to by name in blender (they may be internally reordered, so we can't rely on the ordering).

In order to import animations, they need to have the "num_joints" and "ofs_joints" chunk which defines the joint names. If you don't have access to the original IQE files, you can convert the IQM animations to IQE and copy-paste the bone names from the main rig (copy all the lines beginning with  "joint" and paste them after the header, before the "animation" line). Then you should be able to import them in blender.

**Comment by poVoq** [comment]
Ah, good to know that there is a manual work-around with .iqe. Too bad it doesn't work directly though.
